server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      dialect: org.hibernate.dialect.MariaDBDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

# 구글 로그인 설정 추가
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1001411068057-47l6ikaejfa8tng5t1ockre911ofi6h8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 1426227378041700
            client-secret: a623307704c92fd58fb977bb77a2be52
            scope:
              - email
              - public_profile
  # DevTools 설정 추가
  devtools:
    restart:
      enabled: true

logging:
  file:
    encofing: UTF-8
  console:
    encoding: UTF-8
  level:
    root: INFO  # 기본 로그 레벨 설정
    com.cos.security1.controller: DEBUG  # 특정 패키지에 대한 로그 레벨 설정

